version: '2.1'

services:
  mangas-postgres:
    image: postgres:latest
    container_name: mangas-postgres
    environment:
      POSTGRES_DB: mangas-database
      POSTGRES_USER: mangas-app
      POSTGRES_PASSWORD: mangas-app-pwd
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h mangas-postgres -p 5432 -q -U mangas-app -d mangas-database"]
      interval: 10s
      retries: 3
      timeout: 3s

  mangas-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      mangas-postgres:
        condition: service_healthy
    environment:
      DB_HOST: mangas-postgres
      DB_PORT: 5432
      DB_USER: mangas-app
      DB_NAME: mangas-database
      DB_PASSWORD: mangas-app-pwd
